DROP DATABASE IF EXISTS GRUPO2
GO
CREATE DATABASE GRUPO2
GO
USE GRUPO2
GO

CREATE TABLE ALUMNOS(
	DNI CHAR(9) PRIMARY KEY NOT NULL,
	NOMBRE NVARCHAR(20) NOT NULL,
	APELLIDO1 NVARCHAR(30) NOT NULL,
	APELLIDO2 NVARCHAR(30) NOT NULL,
	ID_CICLO SMALLINT NOT NULL,
)

CREATE TABLE CICLOS(
	ID_CICLO SMALLINT PRIMARY KEY,
	NOMBRECICLO NVARCHAR(30) NOT NULL
)

CREATE TABLE MODULOS(
	ID_CICLO SMALLINT NOT NULL,
	ID_MODULO SMALLINT NOT NULL,
	MODULO NVARCHAR(100) NOT NULL
)

CREATE TABLE RA(
	ID_CICLO SMALLINT NOT NULL,
	ID_MODULO SMALLINT NOT NULL,
	ID_RA SMALLINT NOT NULL,
	RA NVARCHAR(100) NOT NULL
)

CREATE TABLE JORNADAS(
	DNI CHAR(9) NOT NULL,
	ID_JORNADA SMALLINT NOT NULL,
	HORAS FLOAT NOT NULL DEFAULT 8 ,
	FECHA_ENTRADA DATETIME NOT NULL CHECK (FECHA_ENTRADA<=GETDATE()),
	ESTADO NVARCHAR(30) NOT NULL CHECK (ESTADO IN ('REALIZADO','SIN EMPEZAR','EN CURSO'))
)

CREATE TABLE TAREAS(
	DNI CHAR(9) NOT NULL,
	ID_JORNADA SMALLINT NOT NULL,
	ID_TAREA SMALLINT NOT NULL,
	HORAS FLOAT NOT NULL ,
	DESCRIPCION NVARCHAR(150) NOT NULL
)

CREATE TABLE TAREA_RA(
	ID_CICLO SMALLINT NOT NULL,
	ID_MODULO SMALLINT NOT NULL,
	ID_RA SMALLINT NOT NULL,
	
	DNI CHAR(9) NOT NULL,
	ID_JORNADA SMALLINT NOT NULL,
	ID_TAREA SMALLINT NOT NULL
)

ALTER TABLE ALUMNOS
ADD CONSTRAINT FK_ALUMNO_CICLO FOREIGN KEY(ID_CICLO) REFERENCES CICLOS(ID_CICLO)

ALTER TABLE MODULOS
ADD CONSTRAINT PK_MODULO PRIMARY KEY(ID_CICLO,ID_MODULO)
ALTER TABLE MODULOS
ADD CONSTRAINT FK_MODULO_CICLO FOREIGN KEY (ID_CICLO) REFERENCES CICLOS(ID_CICLO)

ALTER TABLE RA
ADD CONSTRAINT PK_RA PRIMARY KEY(ID_CICLO,ID_MODULO,ID_RA)
ALTER TABLE RA
ADD CONSTRAINT FK_RA_MODULO FOREIGN KEY(ID_CICLO,ID_MODULO) REFERENCES MODULOS(ID_CICLO,ID_MODULO)

ALTER TABLE JORNADAS
ADD CONSTRAINT PK_JORNADA PRIMARY KEY(DNI,ID_JORNADA)
ALTER TABLE JORNADAS
ADD CONSTRAINT FK_JORNADA_ALUMNO FOREIGN KEY(DNI) REFERENCES ALUMNOS(DNI)

ALTER TABLE TAREAS
ADD CONSTRAINT PK_TAREA PRIMARY KEY(DNI,ID_JORNADA,ID_TAREA)
ALTER TABLE TAREAS
ADD CONSTRAINT FK_TAREA_JORNADA FOREIGN KEY(DNI,ID_JORNADA) REFERENCES JORNADAS(DNI,ID_JORNADA)

ALTER TABLE TAREA_RA
ADD CONSTRAINT PK_TAREARA PRIMARY KEY(ID_RA,ID_CICLO,ID_MODULO,DNI,ID_JORNADA,ID_TAREA)
ALTER TABLE TAREA_RA
ADD CONSTRAINT FK_TAREARA_RA FOREIGN KEY(ID_CICLO,ID_MODULO,ID_RA) REFERENCES RA(ID_CICLO,ID_MODULO,ID_RA)
ALTER TABLE TAREA_RA
ADD CONSTRAINT FK_TAREARA_TAREA FOREIGN KEY(DNI,ID_JORNADA,ID_TAREA) REFERENCES TAREAS(DNI,ID_JORNADA,ID_TAREA)
go
CREATE RULE DNIS AS(@CAMPO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')
go
EXEC SP_BINDRULE	DNIS,'TAREAS.DNI'
EXEC SP_BINDRULE	DNIS,'ALUMNOS.DNI'
EXEC SP_BINDRULE	DNIS,'JORNADAS.DNI'
go
CREATE RULE HORAS AS(@HORA BETWEEN 0 AND 8)
go
EXEC SP_BINDRULE	HORAS,'TAREAS.HORAS'
EXEC SP_BINDRULE	HORAS,'JORNADAS.HORAS'


