DROP DATABASE IF EXISTS GRUPO2
GO
CREATE DATABASE GRUPO2
GO
USE GRUPO2
GO

CREATE TABLE ALUMNOS(
	DNI CHAR(9) PRIMARY KEY NOT NULL,
	NOMBRE NVARCHAR(20) NOT NULL,
	APELLIDO1 NVARCHAR(30) NOT NULL,
	APELLIDO2 NVARCHAR(30) NOT NULL,
	ID_CICLO SMALLINT NOT NULL,
)

CREATE TABLE CICLOS(
	ID_CICLO SMALLINT PRIMARY KEY,
	NOMBRECICLO NVARCHAR(30) NOT NULL
)

CREATE TABLE MODULOS(
	ID_CICLO SMALLINT NOT NULL,
	ID_MODULO SMALLINT NOT NULL,
	MODULO NVARCHAR(100) NOT NULL
)

CREATE TABLE RA(
	ID_CICLO SMALLINT NOT NULL,
	ID_MODULO SMALLINT NOT NULL,
	ID_RA SMALLINT NOT NULL,
	RA NVARCHAR(100) NOT NULL
)

CREATE TABLE JORNADAS(
	DNI CHAR(9) NOT NULL,
	ID_JORNADA SMALLINT NOT NULL,
	HORAS FLOAT NOT NULL DEFAULT 8 ,
	FECHA_ENTRADA DATETIME NOT NULL CHECK (FECHA_ENTRADA<=GETDATE()),
	ESTADO NVARCHAR(30) NOT NULL CHECK (ESTADO IN ('REALIZADO','SIN EMPEZAR','EN CURSO'))
)

CREATE TABLE TAREAS(
	DNI CHAR(9) NOT NULL,
	ID_JORNADA SMALLINT NOT NULL,
	ID_TAREA SMALLINT NOT NULL,
	HORAS FLOAT NOT NULL ,
	DESCRIPCION NVARCHAR(150) NOT NULL
)

CREATE TABLE TAREA_RA(
	ID_CICLO SMALLINT NOT NULL,
	ID_MODULO SMALLINT NOT NULL,
	ID_RA SMALLINT NOT NULL,
	
	DNI CHAR(9) NOT NULL,
	ID_JORNADA SMALLINT NOT NULL,
	ID_TAREA SMALLINT NOT NULL
)

ALTER TABLE ALUMNOS
ADD CONSTRAINT FK_ALUMNO_CICLO FOREIGN KEY(ID_CICLO) REFERENCES CICLOS(ID_CICLO)

ALTER TABLE MODULOS
ADD CONSTRAINT PK_MODULO PRIMARY KEY(ID_CICLO,ID_MODULO)
ALTER TABLE MODULOS
ADD CONSTRAINT FK_MODULO_CICLO FOREIGN KEY (ID_CICLO) REFERENCES CICLOS(ID_CICLO)

ALTER TABLE RA
ADD CONSTRAINT PK_RA PRIMARY KEY(ID_CICLO,ID_MODULO,ID_RA)
ALTER TABLE RA
ADD CONSTRAINT FK_RA_MODULO FOREIGN KEY(ID_CICLO,ID_MODULO) REFERENCES MODULOS(ID_CICLO,ID_MODULO)

ALTER TABLE JORNADAS
ADD CONSTRAINT PK_JORNADA PRIMARY KEY(DNI,ID_JORNADA)
ALTER TABLE JORNADAS
ADD CONSTRAINT FK_JORNADA_ALUMNO FOREIGN KEY(DNI) REFERENCES ALUMNOS(DNI)

ALTER TABLE TAREAS
ADD CONSTRAINT PK_TAREA PRIMARY KEY(DNI,ID_JORNADA,ID_TAREA)
ALTER TABLE TAREAS
ADD CONSTRAINT FK_TAREA_JORNADA FOREIGN KEY(DNI,ID_JORNADA) REFERENCES JORNADAS(DNI,ID_JORNADA)

ALTER TABLE TAREA_RA
ADD CONSTRAINT PK_TAREARA PRIMARY KEY(ID_RA,ID_CICLO,ID_MODULO,DNI,ID_JORNADA,ID_TAREA)
ALTER TABLE TAREA_RA
ADD CONSTRAINT FK_TAREARA_RA FOREIGN KEY(ID_CICLO,ID_MODULO,ID_RA) REFERENCES RA(ID_CICLO,ID_MODULO,ID_RA)
ALTER TABLE TAREA_RA
ADD CONSTRAINT FK_TAREARA_TAREA FOREIGN KEY(DNI,ID_JORNADA,ID_TAREA) REFERENCES TAREAS(DNI,ID_JORNADA,ID_TAREA)
go
CREATE RULE DNIS AS(@CAMPO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')
go
EXEC SP_BINDRULE	DNIS,'TAREAS.DNI'
EXEC SP_BINDRULE	DNIS,'ALUMNOS.DNI'
EXEC SP_BINDRULE	DNIS,'JORNADAS.DNI'
go
CREATE RULE HORAS AS(@HORA BETWEEN 0 AND 8)
go
EXEC SP_BINDRULE	HORAS,'TAREAS.HORAS'
EXEC SP_BINDRULE	HORAS,'JORNADAS.HORAS'





-- PROCEDIMIENTO 1: Insertar CICLO

CREATE PROCEDURE PA_INSERTAR_CICLO
    @NOMBRE NVARCHAR(30)
AS
    IF EXISTS (SELECT ID_CICLO FROM CICLOS WHERE NOMBRECICLO = @NOMBRE)
        PRINT 'Ya existe un ciclo con este nombre'
    ELSE
    BEGIN
        DECLARE @NUEVO_ID SMALLINT
        SELECT @NUEVO_ID = ISNULL(MAX(ID_CICLO), 0) + 1
        FROM CICLOS

        INSERT INTO CICLOS (ID_CICLO, NOMBRECICLO)
        VALUES (@NUEVO_ID, @NOMBRE)
    END
-- LLAMADA
PA_INSERTAR_CICLO 'DESARROLLO DE APLICACIONES WEB'
PA_INSERTAR_CICLO 'SISTEMAS MICROINFORMÁTICOS'


-- PROCEDIMIENTO 2: Insertar MODULO

CREATE PROCEDURE PA_INSERTAR_MODULO
    @NOMBRE_CICLO NVARCHAR(30),
    @NOMBRE_MODULO NVARCHAR(100)
AS
    DECLARE @ID_CICLO SMALLINT
    SELECT @ID_CICLO = ID_CICLO
    FROM CICLOS
    WHERE NOMBRECICLO = @NOMBRE_CICLO

    IF @ID_CICLO IS NULL
        PRINT 'No existe este ciclo'
    ELSE
    BEGIN
        DECLARE @NUEVO_ID SMALLINT
        SELECT @NUEVO_ID = ISNULL(MAX(ID_MODULO),0) + 1
        FROM MODULOS
        WHERE ID_CICLO = @ID_CICLO

        INSERT INTO MODULOS (ID_CICLO, ID_MODULO, MODULO)
        VALUES (@ID_CICLO, @NUEVO_ID, @NOMBRE_MODULO)
    END
-- LLAMADA
PA_INSERTAR_MODULO 'DESARROLLO DE APLICACIONES WEB', 'BASES DE DATOS'
PA_INSERTAR_MODULO 'DESARROLLO DE APLICACIONES WEB', 'PROGRAMACIÓN'



-- PROCEDIMIENTO 3: Insertar RA

CREATE PROCEDURE PA_INSERTAR_RA
    @NOMBRE_CICLO NVARCHAR(30),
    @NOMBRE_MODULO NVARCHAR(100),
    @TEXTO_RA NVARCHAR(100)
AS
    DECLARE @ID_CICLO SMALLINT
    SELECT @ID_CICLO = ID_CICLO
    FROM CICLOS
    WHERE NOMBRECICLO = @NOMBRE_CICLO

    IF @ID_CICLO IS NULL
    BEGIN
        PRINT 'No existe este ciclo'
        RETURN
    END

    DECLARE @ID_MODULO SMALLINT
    SELECT @ID_MODULO = ID_MODULO
    FROM MODULOS
    WHERE ID_CICLO = @ID_CICLO AND MODULO = @NOMBRE_MODULO

    IF @ID_MODULO IS NULL
        PRINT 'No existe este modulo en el ciclo puesto'
    ELSE
    BEGIN
        DECLARE @NUEVO_ID SMALLINT
        SELECT @NUEVO_ID = ISNULL(MAX(ID_RA), 0) + 1
        FROM RA
        WHERE ID_CICLO = @ID_CICLO AND ID_MODULO = @ID_MODULO

        INSERT INTO RA (ID_CICLO, ID_MODULO, ID_RA, RA)
        VALUES (@ID_CICLO, @ID_MODULO, @NUEVO_ID, @TEXTO_RA)
    END
-- LLAMADA
PA_INSERTAR_RA 'DESARROLLO DE APLICACIONES WEB', 'BASES DE DATOS', 'Crea bases de datos definiendo su estructura'
PA_INSERTAR_RA 'DESARROLLO DE APLICACIONES WEB', 'BASES DE DATOS', 'Realiza consultas sobre una o varias tablas'



-- PROCEDIMIENTO 4: Insertar JORNADA

CREATE PROCEDURE PA_INSERTAR_JORNADA
    @DNI CHAR(9),
    @HORAS FLOAT = 8,
    @FECHA_ENTRADA DATETIME,
    @ESTADO NVARCHAR(30)
AS
    IF NOT EXISTS (SELECT * FROM ALUMNOS WHERE DNI = @DNI)
        PRINT 'No hay alumnos con este dni'
    ELSE
    BEGIN
        DECLARE @NUEVO_ID SMALLINT
        SELECT @NUEVO_ID = ISNULL(MAX(ID_JORNADA), 0) + 1
        FROM JORNADAS
        WHERE DNI = @DNI

        INSERT INTO JORNADAS (DNI, ID_JORNADA, HORAS, FECHA_ENTRADA, ESTADO)
        VALUES (@DNI, @NUEVO_ID, @HORAS, @FECHA_ENTRADA, @ESTADO)
    END
-- LLAMADA
PA_INSERTAR_JORNADA '12345678A', 8, '2024-01-15', 'SIN EMPEZAR'
PA_INSERTAR_JORNADA '12345678A', 5, '2024-01-16', 'EN CURSO'



-- PROCEDIMIENTO 5: Insertar TAREA

CREATE PROCEDURE PA_INSERTAR_TAREA
    @DNI CHAR(9),
    @ID_JORNADA SMALLINT,
    @HORAS FLOAT,
    @DESCRIPCION NVARCHAR(150)
AS
    IF NOT EXISTS (SELECT * FROM JORNADAS WHERE DNI = @DNI AND ID_JORNADA = @ID_JORNADA)
        PRINT 'No existe esa jornada para el alumno puesto'
    ELSE
    BEGIN
        DECLARE @NUEVO_ID SMALLINT
        SELECT @NUEVO_ID = ISNULL(MAX(ID_TAREA), 0) + 1
        FROM TAREAS
        WHERE DNI = @DNI AND ID_JORNADA = @ID_JORNADA

        INSERT INTO TAREAS (DNI, ID_JORNADA, ID_TAREA, HORAS, DESCRIPCION)
        VALUES (@DNI, @ID_JORNADA, @NUEVO_ID, @HORAS, @DESCRIPCION)
    END
-- LLAMADA
PA_INSERTAR_TAREA '12345678A', 1, 3, 'Desarrollo de consultas SQL'
PA_INSERTAR_TAREA '12345678A', 1, 2, 'Corrección de errores en el código'


-- PROCEDIMIENTO 6: Horas totales trabajadas

CREATE PROCEDURE sp_horas_trabajadas
    @NOMBRE    NVARCHAR(20),
    @APELLIDO1 NVARCHAR(40),
    @APELLIDO2 NVARCHAR(40)
AS
    RETURN (
        SELECT SUM(JORNADAS.HORAS)
        FROM   ALUMNOS
               INNER JOIN JORNADAS JORNADAS ON ALUMNOS.DNI = JORNADAS.DNI
        WHERE  ALUMNOS.NOMBRE    = @NOMBRE
          AND  ALUMNOS.APELLIDO1 = @APELLIDO1
          AND  ALUMNOS.APELLIDO2 = @APELLIDO2

        GROUP BY ALUMNOS.NOMBRE, ALUMNOS.APELLIDO1, ALUMNOS.APELLIDO2
        HAVING ALUMNOS.NOMBRE    = @NOMBRE
           AND ALUMNOS.APELLIDO1 = @APELLIDO1
           AND ALUMNOS.APELLIDO2 = @APELLIDO2
    )

-- LLAMADA
DECLARE @HORAS SMALLINT
EXEC @HORAS = sp_horas_trabajadas 'MAXIM', 'PASCAL', 'PASCAL2'
PRINT @HORAS
